import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Nunito_Sans } from "next/font/google";

const nunito_sans = Nunito_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito_sans.variable} font-nunito antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
